version: "3"

services:
  dbMain:
    image: postgres:latest
    restart: always
    ports:
       - 5432:5432
    environment:
      - POSTGRES_DB=storage
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin